version: "3.9"
services:
  zookeeper:
    image: ubuntu
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/dados"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: ubuntu
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/dados"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local